### ISSUE TITLE
missing FOLLY_INCLUDE_DIR FOLLY_LIBRARIES

### ISSUE THREAD

**Issue by alexbw** [facebook/fbcunn#7]
Attempting to install fbcunn on a (relatively) clean Ubuntu 14.01 image that we use for GPU computation on EC2. Already have successfully installed cutorch, cunn, and cunnx, and tested that they are functional.

Running into problems locating FOLLY. I've checked the install script that installs folly, and there are no environment variable updates that occur. Am I missing something?

```
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/whetlab/torch-distro/install
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  REQUIRED_ARGS (missing: FOLLY_INCLUDE_DIR FOLLY_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFolly.cmake:23 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:12 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/whetlab/nn/fbcunn/build/CMakeFiles/CMakeOutput.log".
```

**Comment by soumith** [comment]
i ran into this and i fixed it somehow, cant remember now ugh! 

if i remember, installing folly again fixed it! (wtf!)

**Comment by alexbw** [comment]
We're so far doing fine without fbcunn, so I'll just monitor this thread in
case a definite fix is found.

**Comment by soumith** [comment]
sounds good! thanks for the report

**Comment by ssakhavi** [comment]
Hi,

My problem was that my my compiler was using an older version of  ```gcc```. I upgraded and it worked

**Comment by alexbw** [comment]
What version? I was compiling with gcc 4.8, and still failed.

**Comment by ssakhavi** [comment]
Yes. I think another thing I did was to run the installation from the folly
directory.

**Comment by alexbw** [comment]
So 4.8 is the old version, and 4.9 is the new version that worked?

**Comment by ssakhavi** [comment]
No. GCC itself is 4.8.2.

Just install  ```build-essential``` again to update or download the
repository and install it manually.

**Comment by tohnperfect** [comment]
I am using GCC v4.8.2 but still got this error.

**Comment by aikuharenko** [comment]
I got the same error. In my case the problem was that folly library wasn't installed during previous installation script which was due to permissions problem. After manual installation of folly everything was ok.

**Comment by gtadiparthi** [comment]
Got the same error. As soumith pointed out, installed folly again. Fixed it.

**Comment by hopestar** [comment]
i am usring gcc (GCC) 5.1.0 still got the same error ~ o(╯□╰)o

**Comment by ssakhavi** [comment]
@soumith , @hopestar I actually tried installing this library for another computer. what I did was manually install all the dependencies instead using the bash file. and it worked.

**Comment by bamos** [comment]
Same experience as @ssakhavi - the `libboost1.55-all-dev` line in
https://github.com/soumith/fblualib/blob/master/install_all.sh
was causing the install to fail.

```
The following packages have unmet dependencies:
 libboost1.55-all-dev : Depends: libboost1.55-dev but it is not going to be installed
                        Depends: libboost1.55-tools-dev
                        Depends: libboost-atomic1.55-dev but it is not going to be installed
                        Depends: libboost-chrono1.55-dev but it is not going to be installed
                        Depends: libboost-context1.55-dev but it is not going to be installed
                        Depends: libboost-coroutine1.55-dev but it is not going to be installed
                        Depends: libboost-date-time1.55-dev but it is not going to be installed
                        Depends: libboost-exception1.55-dev but it is not going to be installed
                        Depends: libboost-filesystem1.55-dev but it is not going to be installed
                        Depends: libboost-graph1.55-dev but it is not going to be installed
                        Depends: libboost-graph-parallel1.55-dev but it is not going to be installed
                        Depends: libboost-iostreams1.55-dev but it is not going to be installed
                        Depends: libboost-locale1.55-dev but it is not going to be installed
                        Depends: libboost-log1.55-dev but it is not going to be installed
                        Depends: libboost-math1.55-dev but it is not going to be installed
                        Depends: libboost-mpi1.55-dev but it is not going to be installed
                        Depends: libboost-mpi-python1.55-dev but it is not going to be installed
                        Depends: libboost-program-options1.55-dev but it is not going to be installed
                        Depends: libboost-python1.55-dev but it is not going to be installed
                        Depends: libboost-random1.55-dev but it is not going to be installed
                        Depends: libboost-regex1.55-dev but it is not going to be installed
                        Depends: libboost-serialization1.55-dev but it is not going to be installed
                        Depends: libboost-signals1.55-dev but it is not going to be installed
                        Depends: libboost-system1.55-dev but it is not going to be installed
                        Depends: libboost-test1.55-dev but it is not going to be installed
                        Depends: libboost-thread1.55-dev but it is not going to be installed
                        Depends: libboost-timer1.55-dev but it is not going to be installed
                        Depends: libboost-wave1.55-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Even though `-e` is in the hashbang, I was confused
why the script isn't exiting nonzero when this is
encountered, since `apt-get` returns 100.
I've realized this is because the interpreter in the
hashbang is being ignored by piping curl's output
into `bash` instead of `bash -e` in
https://github.com/facebook/fbcunn/blob/master/INSTALL.md.
I submitted a PR to use `bash -e`.

**Comment by pedropgusmao** [comment]
If you run `sudo ldconfig` after installing the folly library it will let the linker cache and now about the newly installed library, which in turn will let thrift find it.  It worked for me, so I propose the inclusion o `sudo ldconfig` after each library installation =).

Have a nice day.

**Comment by sunshineatnoon** [comment]
The [install_all.sh](https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh) seems only support Ubuntu 13.10 or 14.*, I'm on Ubuntu 16.04, so how can I install folly then? THX.
